### ISSUE TITLE
Deserialization failed

### ISSUE THREAD

**Issue by siphonelee** [MystenLabs/sui-rust-sdk#69]
Hi team,

Great job with the Rust SDK and it helped me a lot!

Recently I found an issue, which appeared to be related to sui version upgrade. With the code below I got this error:
```
ERROR commonlib::move_call] Parse error: Deserialization failed at line 1 column 5290
```
```rust
    let transaction_response = sui
        .quorum_driver_api()
        .execute_transaction_block(
            Transaction::from_data(tx_data, vec![signature]),
            SuiTransactionBlockResponseOptions::full_content(),
            Some(ExecuteTransactionRequestType::WaitForLocalExecution),
        )
        .await.map_err(|e| {
            log::error!("{}", e);
            SuiError{value: SuiErrorValue::TransactionBlockExecuteError}
        })?;
```

Some info:
1. A couple days ago with Walrus CLI I suddenly saw this same error too when executing command "walrus info", but when I upgrade Walrus to latest version (1.5.2-c3f937f0238b), the error disappeared;
2. When I changed Walrus config file (~/.sui/sui_config/client.yaml) to use another sui testnet RPC endpoint other than "https://fullnode.testnet.sui.io:443", like "https://sui-testnet.public.blastapi.io:443", the error disappeared.

So I assume the testnet RPC endpoint https://fullnode.testnet.sui.io:443 had some breaking changes and the SDK needs to accommodate the changes as well.

**Comment by bmwill** [comment]
This is due to this recent change documented [here](https://forums.sui.io/t/breaking-change-alert-consistently-encode-binary-data-with-base64-in-json-rpc/46734). Given you're using rust you should just need to update your dependency to the latest 1.39.1 release to no longer be affected by the deserialization failure error.

**Comment by siphonelee** [comment]
> This is due to this recent change documented [here](https://forums.sui.io/t/breaking-change-alert-consistently-encode-binary-data-with-base64-in-json-rpc/46734). Given you're using rust you should just need to update your dependency to the latest 1.39.1 release to no longer be affected by the deserialization failure error.

@bmwill Thank you for the quick response! Version upgrading did resolve the issue.
