### ISSUE TITLE
Could the sui-sdk be migrated here?

### ISSUE THREAD

**Issue by lispking** [MystenLabs/sui-rust-sdk#78]
Could the [sui-sdk](https://github.com/MystenLabs/sui/tree/main/crates/sui-sdk) be migrated here? 

In this way, it will be convenient for other libraries to conduct secondary encapsulation.

**Comment by stefan-mysten** [comment]
No, this is a full rewrite of the `sui-sdk`. JSON RPC will not be supported at some point and we'll have to move to GraphQL, thus this new complete SDK with GraphQL client support.

**Comment by lispking** [comment]
cool, are there any functions that need to be developed at an accelerated pace currently? 

Is this SDK ready for use now? I've just finished developing the Rust SDK for Deepbook recently. 

However, it was developed based on the original sui-sdk, and I found it too bulky. 

I want to replace it with this one. I'm not sure whether it can be used or not.  @stefan-mysten

**Comment by bmwill** [comment]
> Is this SDK ready for use now? 

Its still under development, but there is enough functionality to build/sign transactions but functionality for interacting with an RPC is limited at the moment and an area we're working on improving. I'm hoping for a lot of things to improve here over the next few weeks. In the meantime feel free to take a look and file issues for things you find missing/lacking and we'll work on filling the gaps!

> However, it was developed based on the original sui-sdk, and I found it too bulky.

Yep this is exactly the reason why this project was started, to provide a lighter-weight base for people building on Sui.

**Comment by stefan-mysten** [comment]
That's awesome, thanks for the context @lispking. 

> Is this SDK ready for use now? I've just finished developing the Rust SDK for Deepbook recently.
Depends a lot on what you need. 
- If you need the core `sui-sdk-types`, that crate is almost ready to be used and it should be 100% compatible with `sui-types` from `sui` monorepo.
- If you need JSON RPC, that is not really available here, so you can't use that. 
- If you need to use GraphQL, the GraphQL client crate is a very early version that works, but probably does not expose all the needed APIs. However, GraphQL service is not yet fully released, so expect changes to the schema and possible performance issues.

Is your Rust SDK for Deepbook open source? I can have a very quick look to see what you're using there and then I can understand if you could migrate to some of the code from this repo.

**Comment by lispking** [comment]
> That's awesome, thanks for the context @lispking.太棒了，感谢上下文@lispking。
> 
> > Is this SDK ready for use now? I've just finished developing the Rust SDK for Deepbook recently.这个SDK现在可以使用了吗？我最近刚刚完成 Deepbook 的 Rust SDK 的开发。
> > Depends a lot on what you need.很大程度上取决于你的需要。
> 
> * If you need the core `sui-sdk-types`, that crate is almost ready to be used and it should be 100% compatible with `sui-types` from `sui` monorepo.如果您需要核心 `sui-sdk-types` ，该板条箱几乎已准备好使用，并且它应该与 `sui` monorepo 中的 `sui-types` 100% 兼容。
> * If you need JSON RPC, that is not really available here, so you can't use that.如果您需要 JSON RPC，那么这里实际上不可用，因此您不能使用它。
> * If you need to use GraphQL, the GraphQL client crate is a very early version that works, but probably does not expose all the needed APIs. However, GraphQL service is not yet fully released, so expect changes to the schema and possible performance issues.如果您需要使用 GraphQL，GraphQL 客户端 crate 是一个非常早期的版本，可以运行，但可能不会公开所有需要的 API。然而，GraphQL 服务尚未完全发布，因此预计架构会发生变化，并可能出现性能问题。
> 
> Is your Rust SDK for Deepbook open source? I can have a very quick look to see what you're using there and then I can understand if you could migrate to some of the code from this repo.你们的 Deepbook Rust SDK 是开源的吗？我可以非常快速地查看您在那里使用的内容，然后我可以了解您是否可以迁移到此存储库中的某些代码。

https://github.com/lispking/sui-deepbookv3

**Comment by stefan-mysten** [comment]
Yes, PTBs are used a lot in the Deepbook SDK you built, so I would say, you should wait for a bit before migrating as a transaction builder is not fully built up yet in this `sui-rust-sdk` repository.

**Comment by lispking** [comment]
When is it expected to be ready?

**Comment by stefan-mysten** [comment]
We don't have a date yet, sorry.
